Add Laravel 8 support
RingierIMU/state-workflow pull request #14
Opened 2021-04-17 07:27 UTC by percymamedy

- Update composer.json to add Laravel 8
- Add Legacy factories to keep support for Unit tests
- Remove php 7.2 from Contraint and Test Matrix.

2021-04-17 07:33 UTC, atimbang-ROAM approved these changes

2021-04-17 09:00 UTC, datashaman approved these changes

2021-04-17 09:02 UTC, datashaman requested changes

2021-04-17 09:02 UTC, datashaman commented on composer.json
> +        "illuminate/events": "^8.12",
This will force all users to adopt Laravel 8. Use ||.

2021-04-17 09:02 UTC, datashaman commented on composer.json
> +        "orchestra/testbench": "^6.0",
orchestra testbench versions must be specified in same steps as laravel's

2021-04-29 07:02 UTC, datashaman approved these changes

2021-04-29 07:03 UTC, datashaman commented on .github/workflows/main.yml
>            - php: 7.4
is this exclusion still valid?

2021-04-29 07:31 UTC, merged